# Generated by Django 5.2.8 on 2025-11-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardItem',
            new_name='Card_item',
        ),
        migrations.AlterField(
            model_name='card',
            name='card_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
